# Generated by Django 5.1.15 on 2026-07-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pickup_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="dining_mode",
            field=models.CharField(
                blank=True,
                choices=[("takeaway", "外带自取"), ("dine_in", "到店堂食")],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
    ]
