# Generated by Django 5.1.15 on 2026-07-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_pickup_time_order_dining_mode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "订单菜品", "verbose_name_plural": "订单菜品"},
        ),
    ]
