# Generated by Django 5.1.15 on 2026-07-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "菜品分类",
                "verbose_name_plural": "菜品分类",
            },
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={
                "ordering": ["category__sort_order", "sort_order", "id"],
                "verbose_name": "菜品",
                "verbose_name_plural": "菜品",
            },
        ),
    ]
